name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install pre-commit
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          python3 -m pipx install pre-commit
      - name: Add path for Python packages
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Run linters
        run: |
          pre-commit run --all-files
